Metrics/MethodLength:
  Max: 70

Metrics/ModuleLength:
  Max: 200

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/AbcSize:
  Max: 70
