version: '3.6'
services:
  db:
    image: postgres:10.5-alpine
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT

  app:
    build:
      context: ./
    command: >
      bash -c "
      bundle check
      || bundle install --clean
      && rm -f tmp/pids/server.pid
      && bundle exec rails server"
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
    environment:
      BUNDLE_PATH: /app/gems
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8099:8099

volumes:
  postgres:
