default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('POSTGRES_POOL') { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= "#{ENV['POSTGRES_DB']}_test" %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
